databases:
  - name: doctor_n_c&c_app
    databaseName: doctor_n_c&c_app
    user: doctor_n_c&c_app_user
    plan: free

services:
  - type: web
    name: doctor_n_c&c_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctor_n_c&c_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default